CRITICAL - 2024-07-04 10:55:42 --> Error: Class "App\Controllers\baseController" not found
in APPPATH/Controllers/utama.php on line 7.
 1 SYSTEMPATH/Autoloader/Autoloader.php(311): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile()
 3 SYSTEMPATH/Autoloader/Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass()
 5 SYSTEMPATH/CodeIgniter.php(901): class_exists()
 6 SYSTEMPATH/CodeIgniter.php(490): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-04 11:31:44 --> Error: Class "App\Controllers\baseController" not found
in APPPATH/Controllers/utama.php on line 7.
 1 SYSTEMPATH/Autoloader/Autoloader.php(311): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile()
 3 SYSTEMPATH/Autoloader/Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass()
 5 SYSTEMPATH/CodeIgniter.php(901): class_exists()
 6 SYSTEMPATH/CodeIgniter.php(490): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-04 11:31:50 --> Error: Class "App\Controllers\baseController" not found
in APPPATH/Controllers/utama.php on line 7.
 1 SYSTEMPATH/Autoloader/Autoloader.php(311): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile()
 3 SYSTEMPATH/Autoloader/Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass()
 5 SYSTEMPATH/CodeIgniter.php(901): class_exists()
 6 SYSTEMPATH/CodeIgniter.php(490): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-04 11:32:00 --> Error: Class "App\Controllers\baseController" not found
in APPPATH/Controllers/utama.php on line 7.
 1 SYSTEMPATH/Autoloader/Autoloader.php(311): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile()
 3 SYSTEMPATH/Autoloader/Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass()
 5 SYSTEMPATH/CodeIgniter.php(901): class_exists()
 6 SYSTEMPATH/CodeIgniter.php(490): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-04 11:32:05 --> Error: Class "App\Controllers\baseController" not found
in APPPATH/Controllers/utama.php on line 7.
 1 SYSTEMPATH/Autoloader/Autoloader.php(311): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile()
 3 SYSTEMPATH/Autoloader/Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass()
 5 SYSTEMPATH/CodeIgniter.php(901): class_exists()
 6 SYSTEMPATH/CodeIgniter.php(490): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-04 11:33:00 --> Error: Class "App\Controllers\baseController" not found
in APPPATH/Controllers/utama.php on line 7.
 1 SYSTEMPATH/Autoloader/Autoloader.php(311): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile()
 3 SYSTEMPATH/Autoloader/Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass()
 5 SYSTEMPATH/CodeIgniter.php(901): class_exists()
 6 SYSTEMPATH/CodeIgniter.php(490): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-04 11:33:02 --> Error: Class "App\Controllers\baseController" not found
in APPPATH/Controllers/utama.php on line 7.
 1 SYSTEMPATH/Autoloader/Autoloader.php(311): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile()
 3 SYSTEMPATH/Autoloader/Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass()
 5 SYSTEMPATH/CodeIgniter.php(901): class_exists()
 6 SYSTEMPATH/CodeIgniter.php(490): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-07-04 11:33:04 --> Error: Class "App\Controllers\baseController" not found
in APPPATH/Controllers/utama.php on line 7.
 1 SYSTEMPATH/Autoloader/Autoloader.php(311): include_once()
 2 SYSTEMPATH/Autoloader/Autoloader.php(290): CodeIgniter\Autoloader\Autoloader->includeFile()
 3 SYSTEMPATH/Autoloader/Autoloader.php(266): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
 4 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass()
 5 SYSTEMPATH/CodeIgniter.php(901): class_exists()
 6 SYSTEMPATH/CodeIgniter.php(490): CodeIgniter\CodeIgniter->startController()
 7 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 8 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-04 12:06:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2024-07-04 12:06:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-07-04 12:14:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:14:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:15:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:15:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:16:02 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:16:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:16:02 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:16:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:16:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:16:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:16:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:16:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:17:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:17:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:17:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:17:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:17:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:17:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:17:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:17:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:17:31 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:17:31 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-07-04 12:27:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:27:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-04 12:27:42 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-07-04 12:27:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'sawit_admin'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:187
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(187): mysqli->real_connect('localhost', 'sawit_admin', '5Ahlussunnah6', 'sawit_sawit', 3306, '', 0)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\sawitci4\app\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\sawitci4\app\Controllers\utama.php(33): App\Models\login_m->index()
#5 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\utama->login()
#6 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
#7 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 D:\xampp\htdocs\sawitci4\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 D:\xampp\htdocs\sawitci4\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-07-04 12:27:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1636): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `identity`', [], false)
 3 APPPATH\Models\login_m.php(18): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\utama.php(33): App\Models\login_m->index()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\utama->login()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\utama))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
INFO - 2024-07-04 12:29:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-04 12:29:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-04 12:29:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-07-04 12:29:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
